//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public CLIENTES()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public string Nit { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string IdentificacionVendedor { get; set; }
        public string NombreContacto { get; set; }
    
        public virtual VENDEDORES VENDEDORES { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
