//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGS
    {
        public string TipoTransaccion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Resultado { get; set; }
        public string IdentificacionUsuario { get; set; }
    
        public virtual VENDEDORES VENDEDORES { get; set; }
    }
}
