//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDORES
    {
        public VENDEDORES()
        {
            this.CLIENTES = new HashSet<CLIENTES>();
            this.LOGS = new HashSet<LOGS>();
        }
    
        public string Identificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<CLIENTES> CLIENTES { get; set; }
        public virtual ICollection<LOGS> LOGS { get; set; }
        public virtual VENDEDORES VENDEDORES1 { get; set; }
        public virtual VENDEDORES VENDEDORES2 { get; set; }
    }
}
