//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public PEDIDO()
        {
            this.LISTA_PEDIDO = new HashSet<LISTA_PEDIDO>();
        }
    
        public string Codigo { get; set; }
        public double Total { get; set; }
        public System.DateTime Fecha { get; set; }
        public string NitCliente { get; set; }
        public byte[] Entregado { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<LISTA_PEDIDO> LISTA_PEDIDO { get; set; }
    }
}
