//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VENTASserverdbEntities : DbContext
    {
        public VENTASserverdbEntities()
            : base("name=VENTASserverdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLIENTE> CLIENTES { get; set; }
        public DbSet<LISTA_PEDIDO> LISTA_PEDIDO { get; set; }
        public DbSet<LOG> LOGS { get; set; }
        public DbSet<PEDIDO> PEDIDOes { get; set; }
        public DbSet<PRODUCTO> PRODUCTOS { get; set; }
        public DbSet<USUARIO> USUARIOS { get; set; }
    }
}
