//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.CLIENTES = new HashSet<CLIENTE>();
            this.LOGS = new HashSet<LOG>();
        }
    
        public string Identificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string password { get; set; }
        public string rol { get; set; }
        public Nullable<System.DateTime> ultimaSync { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTES { get; set; }
        public virtual ICollection<LOG> LOGS { get; set; }
        public virtual USUARIO USUARIOS1 { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
